spring:
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: classpath:db/changelog/master.xml
  h2:
    console:
      enabled: true
server:
  port: 8081
tpd:
  userDeletionTopicName: userDeleted